//! Coverage for every supported key name and alias.

use super::string_to_key;
use rdev::Key;

const MAPPINGS: &[(&str, Key)] = &[
    ("ctrl", Key::ControlLeft),
    ("control", Key::ControlLeft),
    ("leftcontrol", Key::ControlLeft),
    ("rctrl", Key::ControlRight),
    ("rightcontrol", Key::ControlRight),
    ("shift", Key::ShiftLeft),
    ("leftshift", Key::ShiftLeft),
    ("rshift", Key::ShiftRight),
    ("rightshift", Key::ShiftRight),
    ("alt", Key::Alt),
    ("option", Key::Alt),
    ("leftalt", Key::Alt),
    ("ralt", Key::AltGr),
    ("rightaltoption", Key::AltGr),
    ("meta", Key::MetaLeft),
    ("super", Key::MetaLeft),
    ("cmd", Key::MetaLeft),
    ("command", Key::MetaLeft),
    ("leftmeta", Key::MetaLeft),
    ("rmeta", Key::MetaRight),
    ("rsuper", Key::MetaRight),
    ("rcmd", Key::MetaRight),
    ("rightmeta", Key::MetaRight),
    ("space", Key::Space),
    ("enter", Key::Return),
    ("return", Key::Return),
    ("tab", Key::Tab),
    ("escape", Key::Escape),
    ("esc", Key::Escape),
    ("backspace", Key::Backspace),
    ("delete", Key::Delete),
    ("del", Key::Delete),
    ("capslock", Key::CapsLock),
    ("fn", Key::Function),
    ("function", Key::Function),
    ("f1", Key::F1),
    ("f2", Key::F2),
    ("f3", Key::F3),
    ("f4", Key::F4),
    ("f5", Key::F5),
    ("f6", Key::F6),
    ("f7", Key::F7),
    ("f8", Key::F8),
    ("f9", Key::F9),
    ("f10", Key::F10),
    ("f11", Key::F11),
    ("f12", Key::F12),
    ("up", Key::UpArrow),
    ("uparrow", Key::UpArrow),
    ("down", Key::DownArrow),
    ("downarrow", Key::DownArrow),
    ("left", Key::LeftArrow),
    ("leftarrow", Key::LeftArrow),
    ("right", Key::RightArrow),
    ("rightarrow", Key::RightArrow),
    ("home", Key::Home),
    ("end", Key::End),
    ("pageup", Key::PageUp),
    ("pgup", Key::PageUp),
    ("pagedown", Key::PageDown),
    ("pgdn", Key::PageDown),
    ("insert", Key::Insert),
    ("ins", Key::Insert),
    ("a", Key::KeyA),
    ("b", Key::KeyB),
    ("c", Key::KeyC),
    ("d", Key::KeyD),
    ("e", Key::KeyE),
    ("f", Key::KeyF),
    ("g", Key::KeyG),
    ("h", Key::KeyH),
    ("i", Key::KeyI),
    ("j", Key::KeyJ),
    ("k", Key::KeyK),
    ("l", Key::KeyL),
    ("m", Key::KeyM),
    ("n", Key::KeyN),
    ("o", Key::KeyO),
    ("p", Key::KeyP),
    ("q", Key::KeyQ),
    ("r", Key::KeyR),
    ("s", Key::KeyS),
    ("t", Key::KeyT),
    ("u", Key::KeyU),
    ("v", Key::KeyV),
    ("w", Key::KeyW),
    ("x", Key::KeyX),
    ("y", Key::KeyY),
    ("z", Key::KeyZ),
    ("0", Key::Num0),
    ("1", Key::Num1),
    ("2", Key::Num2),
    ("3", Key::Num3),
    ("4", Key::Num4),
    ("5", Key::Num5),
    ("6", Key::Num6),
    ("7", Key::Num7),
    ("8", Key::Num8),
    ("9", Key::Num9),
];

#[test]
fn maps_every_supported_key_name() {
    for (name, expected) in MAPPINGS {
        assert_eq!(string_to_key(name), Ok(*expected), "key name {name}");
    }
    assert!(string_to_key("unknown").is_err());
    assert_eq!(string_to_key("F5"), Ok(Key::F5));
}
