//! Key-name table for [`parse_hotkey`](super::parse_hotkey).

use rdev::Key;

/// Convert a string key name to an rdev Key.
pub(super) fn string_to_key(s: &str) -> crate::Result<Key> {
    match s.to_lowercase().as_str() {
        // Modifiers
        "ctrl" | "control" | "leftcontrol" => Ok(Key::ControlLeft),
        "rctrl" | "rightcontrol" => Ok(Key::ControlRight),
        "shift" | "leftshift" => Ok(Key::ShiftLeft),
        "rshift" | "rightshift" => Ok(Key::ShiftRight),
        "alt" | "option" | "leftalt" => Ok(Key::Alt),
        "ralt" | "rightaltoption" => Ok(Key::AltGr),
        "meta" | "super" | "cmd" | "command" | "leftmeta" => Ok(Key::MetaLeft),
        "rmeta" | "rsuper" | "rcmd" | "rightmeta" => Ok(Key::MetaRight),

        // Common keys
        "space" => Ok(Key::Space),
        "enter" | "return" => Ok(Key::Return),
        "tab" => Ok(Key::Tab),
        "escape" | "esc" => Ok(Key::Escape),
        "backspace" => Ok(Key::Backspace),
        "delete" | "del" => Ok(Key::Delete),
        "capslock" => Ok(Key::CapsLock),
        "fn" | "function" => Ok(Key::Function),

        // F-keys
        "f1" => Ok(Key::F1),
        "f2" => Ok(Key::F2),
        "f3" => Ok(Key::F3),
        "f4" => Ok(Key::F4),
        "f5" => Ok(Key::F5),
        "f6" => Ok(Key::F6),
        "f7" => Ok(Key::F7),
        "f8" => Ok(Key::F8),
        "f9" => Ok(Key::F9),
        "f10" => Ok(Key::F10),
        "f11" => Ok(Key::F11),
        "f12" => Ok(Key::F12),

        // Navigation
        "up" | "uparrow" => Ok(Key::UpArrow),
        "down" | "downarrow" => Ok(Key::DownArrow),
        "left" | "leftarrow" => Ok(Key::LeftArrow),
        "right" | "rightarrow" => Ok(Key::RightArrow),
        "home" => Ok(Key::Home),
        "end" => Ok(Key::End),
        "pageup" | "pgup" => Ok(Key::PageUp),
        "pagedown" | "pgdn" => Ok(Key::PageDown),
        "insert" | "ins" => Ok(Key::Insert),

        // Letters
        "a" => Ok(Key::KeyA),
        "b" => Ok(Key::KeyB),
        "c" => Ok(Key::KeyC),
        "d" => Ok(Key::KeyD),
        "e" => Ok(Key::KeyE),
        "f" => Ok(Key::KeyF),
        "g" => Ok(Key::KeyG),
        "h" => Ok(Key::KeyH),
        "i" => Ok(Key::KeyI),
        "j" => Ok(Key::KeyJ),
        "k" => Ok(Key::KeyK),
        "l" => Ok(Key::KeyL),
        "m" => Ok(Key::KeyM),
        "n" => Ok(Key::KeyN),
        "o" => Ok(Key::KeyO),
        "p" => Ok(Key::KeyP),
        "q" => Ok(Key::KeyQ),
        "r" => Ok(Key::KeyR),
        "s" => Ok(Key::KeyS),
        "t" => Ok(Key::KeyT),
        "u" => Ok(Key::KeyU),
        "v" => Ok(Key::KeyV),
        "w" => Ok(Key::KeyW),
        "x" => Ok(Key::KeyX),
        "y" => Ok(Key::KeyY),
        "z" => Ok(Key::KeyZ),

        // Numbers
        "0" => Ok(Key::Num0),
        "1" => Ok(Key::Num1),
        "2" => Ok(Key::Num2),
        "3" => Ok(Key::Num3),
        "4" => Ok(Key::Num4),
        "5" => Ok(Key::Num5),
        "6" => Ok(Key::Num6),
        "7" => Ok(Key::Num7),
        "8" => Ok(Key::Num8),
        "9" => Ok(Key::Num9),

        other => Err(crate::error::Error::UnknownHotkeyKey(other.to_owned())),
    }
}

#[cfg(test)]
mod test {
    //! Coverage for every supported key name and alias.

    use super::string_to_key;
    use rdev::Key;

    const MAPPINGS: &[(&str, Key)] = &[
        ("ctrl", Key::ControlLeft),
        ("control", Key::ControlLeft),
        ("leftcontrol", Key::ControlLeft),
        ("rctrl", Key::ControlRight),
        ("rightcontrol", Key::ControlRight),
        ("shift", Key::ShiftLeft),
        ("leftshift", Key::ShiftLeft),
        ("rshift", Key::ShiftRight),
        ("rightshift", Key::ShiftRight),
        ("alt", Key::Alt),
        ("option", Key::Alt),
        ("leftalt", Key::Alt),
        ("ralt", Key::AltGr),
        ("rightaltoption", Key::AltGr),
        ("meta", Key::MetaLeft),
        ("super", Key::MetaLeft),
        ("cmd", Key::MetaLeft),
        ("command", Key::MetaLeft),
        ("leftmeta", Key::MetaLeft),
        ("rmeta", Key::MetaRight),
        ("rsuper", Key::MetaRight),
        ("rcmd", Key::MetaRight),
        ("rightmeta", Key::MetaRight),
        ("space", Key::Space),
        ("enter", Key::Return),
        ("return", Key::Return),
        ("tab", Key::Tab),
        ("escape", Key::Escape),
        ("esc", Key::Escape),
        ("backspace", Key::Backspace),
        ("delete", Key::Delete),
        ("del", Key::Delete),
        ("capslock", Key::CapsLock),
        ("fn", Key::Function),
        ("function", Key::Function),
        ("f1", Key::F1),
        ("f2", Key::F2),
        ("f3", Key::F3),
        ("f4", Key::F4),
        ("f5", Key::F5),
        ("f6", Key::F6),
        ("f7", Key::F7),
        ("f8", Key::F8),
        ("f9", Key::F9),
        ("f10", Key::F10),
        ("f11", Key::F11),
        ("f12", Key::F12),
        ("up", Key::UpArrow),
        ("uparrow", Key::UpArrow),
        ("down", Key::DownArrow),
        ("downarrow", Key::DownArrow),
        ("left", Key::LeftArrow),
        ("leftarrow", Key::LeftArrow),
        ("right", Key::RightArrow),
        ("rightarrow", Key::RightArrow),
        ("home", Key::Home),
        ("end", Key::End),
        ("pageup", Key::PageUp),
        ("pgup", Key::PageUp),
        ("pagedown", Key::PageDown),
        ("pgdn", Key::PageDown),
        ("insert", Key::Insert),
        ("ins", Key::Insert),
        ("a", Key::KeyA),
        ("b", Key::KeyB),
        ("c", Key::KeyC),
        ("d", Key::KeyD),
        ("e", Key::KeyE),
        ("f", Key::KeyF),
        ("g", Key::KeyG),
        ("h", Key::KeyH),
        ("i", Key::KeyI),
        ("j", Key::KeyJ),
        ("k", Key::KeyK),
        ("l", Key::KeyL),
        ("m", Key::KeyM),
        ("n", Key::KeyN),
        ("o", Key::KeyO),
        ("p", Key::KeyP),
        ("q", Key::KeyQ),
        ("r", Key::KeyR),
        ("s", Key::KeyS),
        ("t", Key::KeyT),
        ("u", Key::KeyU),
        ("v", Key::KeyV),
        ("w", Key::KeyW),
        ("x", Key::KeyX),
        ("y", Key::KeyY),
        ("z", Key::KeyZ),
        ("0", Key::Num0),
        ("1", Key::Num1),
        ("2", Key::Num2),
        ("3", Key::Num3),
        ("4", Key::Num4),
        ("5", Key::Num5),
        ("6", Key::Num6),
        ("7", Key::Num7),
        ("8", Key::Num8),
        ("9", Key::Num9),
    ];

    #[test]
    fn maps_every_supported_key_name() {
        for (name, expected) in MAPPINGS {
            assert_eq!(string_to_key(name), Ok(*expected), "key name {name}");
        }
        assert!(string_to_key("unknown").is_err());
        assert_eq!(string_to_key("F5"), Ok(Key::F5));
    }
}
